# Site settings
title: "Cody Ethan Jordan"
author: "Cody Ethan Jordan"
description: "Portfolio for physics and programming projects."
keywords: "Physics, Programming, Game Design, Unity3D, Quantum Computing, Quantum Information, Portflio, CV"
biography: "I am a physicist. TODO write more"
colophon: ""

baseurl: ""
url: "http://codyethanjordan.com"

github_username: CodyEthanJordan
linkedin_username: CodyEthanJordan

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
