# Site settings
title: "Cody Ethan Jordan"
author: "Cody Ethan Jordan"
description: "Portfolio for physics and programming projects. General thoughts. <a href='/'>Back to home</a>"
keywords: "Physics, Programming, Game Design, Unity3D, Quantum Computing, Quantum Information, Portflio, CV"
biography: "I am an apisiring physicist with a background in and programming. <a href='assets/CJordan_CV.pdf'>Read my CV</a> or check through my <a href='/blog'>blog</a> and <a href='/code'>projects</a> for more details."
colophon: ""

baseurl: ""
url: "http://codyethanjordan.com"

github_username: CodyEthanJordan
linkedin_username: CodyEthanJordan

markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:day/:title/
